SELECT 			BILLING_CLASS
				,AVG (TOTAL_CHARGES_AND_CREDITS) AS AVG_TOTAL_CHARGES_AND_CREDITS

FROM			(
				SELECT			A.INSTALLATION_NUMBER
								,A.BILLING_CLASS
								,SUM(TOTAL_CHARGES_AND_CREDITS) AS TOTAL_CHARGES_AND_CREDITS

				FROM 			COMMERCIAL.HNODS_ST_BILL_LATEST_BILLS A
				LEFT JOIN 		COMMERCIAL.HNODS_ST_BILL_ALL_BILLS B
				
				ON 				A.BILL_DOC_NUMBER = B.BILL_DOC_NUMBER 

--STATE				
				WHERE 			B.INSTALLATION_STATE = 'WA'

--TIME PERIOD
				AND 			A.START_BILLING_PERIOD >= '2018-08-01'
				AND 			A.END_BILLING_PERIOD <= '2019-08-01'
				
				GROUP BY		A.INSTALLATION_NUMBER
								,A.BILLING_CLASS
				)
				
GROUP BY		BILLING_CLASS
