SELECT DISTINCT A.STARTDATE AS DATE_MISSING, A.NMI, A.MDPID FROM "DATAINT"."TBL_MISSINGREADS" A 
JOIN "CUSTOMER"."EUITRANS" B
ON SUBSTRING(B.EXT_UI,1,10) = A.NMI 

JOIN "COMMERCIAL"."EUIINSTLN" C 
ON B.INT_UI = C.INT_UI 

JOIN "COMMERCIAL"."EVER" D 
ON C.ANLAGE = D.ANLAGE

LEFT JOIN (SELECT DISTINCT NMI,CALDAY FROM "DATAINT"."TBL_SMAPROF" WHERE SUFFIX = 'E1') NMI
ON A.NMI = NMI.NMI
AND A.STARTDATE = NMI.CALDAY

JOIN "COMMERCIAL"."EANLH"  L
ON D.ANLAGE = L.ANLAGE

WHERE A.STARTDATE >= ADD_DAYS(CURRENT_DATE, -30) AND D.AUSZDAT = '99991231' AND D.BEGRU = 'ZCNI'
AND L.ABLEINH != 'UMS1'
AND NMI.NMI IS NULL
