SELECT E.VERTRAG, E.BELNR, E.ERDAT, E.VKONT, E.GPARTNER, DB3.NETTOBTR, BUT.NAME_ORG1
FROM DATAINT.TBL_SAPISU_DBERCHZ1 DB1
JOIN COMMERCIAL.ERCH E
ON DB1.BELNR = E.BELNR
AND E.STORNODAT = '00000000'
AND E.SIMULATION = ''
AND E.ERDAT >= '20171001'
JOIN CUSTOMER.ISU_BUT000 BUT
ON BUT.PARTNER = E.GPARTNER
JOIN DATAINT.TBL_SAPISU_DBERCHZ3 DB3
ON DB3.BELNR = DB1.BELNR
AND DB3.BELZEILE = DB1.BELZEILE
AND DB1.BELZART = 'ZOETAT'
AND DB3.NETTOBTR != 0
