SELECT YEAR(ERDAT) AS YEAR,MONTH(ERDAT) AS MONTH, COUNT(*) FROM COMMERCIAL.ERCH
WHERE BEGRU = 'ZCNI'
AND ABRVORG = '03'
AND ERDAT >= '2018-01-01'
AND SPARTE = '01'
GROUP BY YEAR(ERDAT),MONTH(ERDAT)
ORDER BY YEAR(ERDAT),MONTH(ERDAT)
