DROP TABLE SP_COMMERCIAL.ALL_BILLS_RN;

CREATE TABLE SP_COMMERCIAL.ALL_BILLS_RN AS (

SELECT *,
	ROW_NUMBER() OVER (PARTITION BY
	BUSINESS_PARTNER_NUMBER,
	CONTRACT_ACCOUNT_NUMBER,
	CONTRACT_NUMBER
	ORDER BY PRINT_DATE DESC) AS RN
FROM COMMERCIAL.HNODS_ST_BILL_ALL_BILLS

--Qualifiers
WHERE PRINT_DATE > '20180101'
AND INSTALLATION_STATE = 'NSW'
);


---


DROP TABLE SP_COMMERCIAL.ALL_BILLS_RN_JOIN;

CREATE TABLE SP_COMMERCIAL.ALL_BILLS_RN_JOIN AS (

SELECT A.*, B.PRINT_DATE AS PRINT_DATE2, DAYS_BETWEEN(B.PRINT_DATE,A.PRINT_DATE) AS DAYS_DIFF
FROM
(SELECT *
FROM SP_COMMERCIAL.ALL_BILLS_RN

--Qualifier
WHERE PRINT_DATE >= '20200101'
AND RN = '1') AS A

LEFT JOIN SP_COMMERCIAL.ALL_BILLS_RN AS B
ON A.BUSINESS_PARTNER_NUMBER = B.BUSINESS_PARTNER_NUMBER 
AND A.CONTRACT_ACCOUNT_NUMBER = B.CONTRACT_ACCOUNT_NUMBER 
AND A.CONTRACT_NUMBER = B.CONTRACT_NUMBER 
AND B.RN = '2'

);

---

--Finding last bill that is 100+ days
SELECT A.*, B.PREMISEPOSTCODE
FROM SP_COMMERCIAL.ALL_BILLS_RN_JOIN A
JOIN "SP_CUSTOMER"."CIA_TheTruthAboutCustomer" B
ON B.CONTRACTACCOUNTNUMBER = A.CONTRACT_ACCOUNT_NUMBER
WHERE DAYS_DIFF > '100'
ORDER BY DAYS_DIFF;


--No last bill or last bill before 01/01/2018
SELECT A.*, B.PREMISEPOSTCODE
FROM
(SELECT *
FROM SP_COMMERCIAL.ALL_BILLS_RN_JOIN
WHERE DAYS_DIFF IS NULL

--Change to 100 days prior to the start of when you're looking for
AND CONTRACT_START_DATE <= '20190923') AS A

JOIN "SP_CUSTOMER"."CIA_TheTruthAboutCustomer" B
ON B.CONTRACTACCOUNTNUMBER = A.CONTRACT_ACCOUNT_NUMBER
