/*======================================================================================================
Stored Procedure Name:            dbo.USP_INSERT_AER_MISSED_POT
Author:                           Shirsha Chakraborty
Create date:                      01/03/2019
Description:                      Customers who missed Pay On Time Discounts
Frequency:                        Quaterly
NOTE:-
      1. Please Change the Parameter passed to the stored procedure based on reporting period you are trying to run.
      2. It can be Run for any Quarter/Year as well replacing Start Date with first day of quarter/year and 
         End Date with Last date of quarter/year.
Template:-
      EXEC dbo.USP_INSERT_AER_MISSED_POT 'Quarter-Start-Date', 'Quarter-End-Date'
Example:-
      EXEC dbo.USP_INSERT_AER_MISSED_POT '20181001', '20181231'
======================================================================================================*/
-- Create the stored procedure in the specified schema
CREATE PROCEDURE [dbo].[USP_INSERT_AER_MISSED_POT]
   @QUARTER_START_DATE VARCHAR(8),
   @QUARTER_END_DATE VARCHAR(8)
-- add more stored procedure parameters here
AS
BEGIN
/*=====================================================================================================
      1. Invoices of customer having Due Date with-in a given Date Range
      Q2-Count -> 4,648,326
=====================================================================================================*/

SELECT ERDK.ZZ_STATE AS REGION
      ,ERCH.GPARTNER AS BP
      ,ERCH.VKONT AS CA
	,ERCH.BUKRS AS COMPANY_CODE
      ,ERCH.VERTRAG AS CONTRACT
      ,ERCH.SPARTE AS FUEL
      ,ERCH.BELNR AS BILL_DOC
      ,ERDK.OPBEL AS INVOICE
      ,ERCH.BEGABRPE AS BILL_START_DATE
      ,ERCH.ENDABRPE AS BILL_END_DATE
	,CAST(ERDK.TOTAL_AMNT AS MONEY) AS TOTAL_AMT_DUE
      ,ERDK.FAEDN AS DUE_DATE
      INTO #INVOICES_DUE FROM 
      ip1.ERCH AS ERCH
      JOIN
      ip1.ERCHC AS ERCHC ON ERCH.MANDT=ERCHC.MANDT AND ERCH.BELNR=ERCHC.BELNR
      JOIN
      ip1.ERDK AS ERDK ON ERCHC.MANDT=ERDK.MANDT AND ERCHC.OPBEL=ERDK.OPBEL
WHERE ERCH.MANDT='100' AND ERCH.TOBRELEASD <> 'X' AND ERCHC.TOBRELEASD <> 'X' AND ERCH.SIMULATION = ''
      AND (ERCH.STORNODAT='00000000' OR (ERCH.STORNODAT<>'00000000' AND ERCH.BCREASON='NA' AND ERCHC.SPCANC='X'))
      AND ERDK.DRUCKDAT<>'00000000' AND (ERDK.ZZ_REPRINT_FNAME<>'' OR ERDK.ZZ_FNAME<>'')
	AND ERDK.FAEDN BETWEEN @QUARTER_START_DATE AND @QUARTER_END_DATE

/*=====================================================================================================
      1. Invoices of Customer who should be getting POT if paid within Due Date.
      2. Remove invoices having POT amount as zero.
      Q2-Count -> 2,846,060
      SELECT DUE_INVOICE.*
            ,(SUM(DBERCHZ3.NETTOBTR)+SUM(DBERCHZ3.NETTOBTR)/10) AS POT_AMOUNT
            INTO #POT_BILL_DETAILS
            FROM 
            #INVOICES_DUE AS DUE_INVOICE
            JOIN
            ip1.DBERCHZ1 AS DBERCHZ1 ON DBERCHZ1.BELNR=DUE_INVOICE.BILL_DOC 
            JOIN
            ip1.DBERCHZ3 AS DBERCHZ3 ON DBERCHZ1.MANDT=DBERCHZ3.MANDT 
            AND DBERCHZ1.BELNR=DBERCHZ3.BELNR
            AND DBERCHZ1.BELZEILE=DBERCHZ3.BELZEILE
      WHERE DBERCHZ1.BUCHREL = '' AND DBERCHZ1.ABSLKZ = '' AND DBERCHZ1.BELZART IN ('ZPCODA','ZPSCDA')
      GROUP BY REGION,BILL_DOC,FUEL,BP,CA,CONTRACT,INVOICE,BILL_START_DATE,BILL_END_DATE,DUE_DATE,TOTAL_AMT_DUE
=====================================================================================================*/
SELECT DUE_INVOICE.*
	,MIN(AB) AS AB
	,MAX(BIS) AS BIS
	,CAST(ROUND((SUM(V_ZAHL3+N_ZAHL3)+SUM(V_ZAHL3+N_ZAHL3)/10),2) AS MONEY) AS POT_AMOUNT 
	INTO #POT_BILL_DETAILS 	FROM 
	#INVOICES_DUE AS DUE_INVOICE
	JOIN
	ip1.DBERCHZ1 AS DBERCHZ1 ON DBERCHZ1.BELNR=DUE_INVOICE.BILL_DOC 
WHERE MANDT ='100' AND BUCHREL = '' AND ABSLKZ = '' AND BELZART IN ('ZPCODA','ZPSCDA')
GROUP BY REGION,BILL_DOC,FUEL,BP,CA,CONTRACT,INVOICE,BILL_START_DATE,BILL_END_DATE,DUE_DATE,TOTAL_AMT_DUE,COMPANY_CODE
/*
-- Q2-Count -> 2,813,310
SELECT * INTO #NON_ZERO_POT_BILL_DETAILS FROM #POT_BILL_DETAILS
WHERE POT_AMOUNT<>'0.00'
*/
/*=====================================================================================================
      1. Assign Product from ISU side to match it compare with CRM
      Q2-Count -> 3,213,187
	SELECT TOP 10 * FROM #NON_ZERO_POT_BILL_DETAILS_WITH_PRODUCT
	DROP TABLE #NON_ZERO_POT_BILL_DETAILS_WITH_PRODUCT
=====================================================================================================*/

SELECT BILLS.*
	,EANLH.AKLASSE AS CUSTOMER_CLASS
      ,EVERH.CRM_OBJECT_ID
      ,CAST(EVERH.CRM_OBJECT_POS AS INT) AS CRM_OBJECT_POS
      ,EVERH.CRM_PRODUCT AS ISU_PRODUCT
      ,EVERH.CONTRACTPOS
      INTO #NON_ZERO_POT_BILL_DETAILS_WITH_PRODUCT FROM 
      #POT_BILL_DETAILS AS BILLS
      LEFT JOIN
      ip1.EVERH AS EVERH 
      ON BILLS.CONTRACT=EVERH.VERTRAG AND (
            (BILLS.AB BETWEEN EVERH.AB AND EVERH.BIS) OR
            (BILLS.BIS BETWEEN EVERH.AB AND EVERH.BIS)
      )
	LEFT JOIN
	ip1.EANLH AS EANLH ON EVERH.MANDT = EANLH.MANDT AND EVERH.ANLAGE = EANLH.ANLAGE 
	AND BILLS.DUE_DATE BETWEEN EANLH.AB AND EANLH.BIS
/*=====================================================================================================
   1. Identify Data having POT attribute populated in CRM system with Contract identified
   2. Std Code to get product attribute
   SELECT RELATIONSHIP.PRODUCT_GUID
         ,ATTRIBUTE.CONFIG_VARIANT
         ,ATTRIBUTE.NAME
         ,ATTRIBUTE.VALID_FROM
         ,ATTRIBUTE.VALID_TO
         ,ATTRIBUTE.DEF_VALUE
         FROM 
         cp1.COMM_PR_FRG_REL AS RELATIONSHIP 
         LEFT JOIN
         cp1.CRM_ISU_ATTR2 AS ATTRIBUTE 
         ON RELATIONSHIP.FRAGMENT_GUID = ATTRIBUTE.FRG_GUID
=====================================================================================================*/
SELECT EXTA4.A4BPNO AS BP
      ,CRM_ITEM.NUMBER_EXT AS CRM_ISU_CONTRACT
      ,CRM_HEADER.OBJECT_ID AS CRM_CONTRACT
      ,CAST(CRM_ITEM.NUMBER_INT AS INT) AS CRM_OBJECT_POS
      ,EXTA4.A4CONTSTART AS CRM_CONTRACT_START_DATE
      ,EXTA4.A4CONTEND AS CRM_CONTRACT_END_DATE
      ,CRM_ITEM.ORDERED_PROD AS PRODUCT
      ,ISU_CONT.ATTR_VALUE AS POT_VALUE
      ,EXTA4.GUID AS ITEM_GUID
      INTO #CRM_POT_CUSTOMER FROM 
      cp1.CRMD_ISUEXTA4 AS EXTA4
      JOIN
      cp1.CRMD_ISU_CONT AS ISU_CONT ON EXTA4.GUID=ISU_CONT.GUID
      JOIN
      cp1.CRMD_ORDERADM_I AS CRM_ITEM ON ISU_CONT.GUID=CRM_ITEM.GUID
      JOIN
      cp1.CRMD_ORDERADM_H AS CRM_HEADER ON CRM_ITEM.HEADER=CRM_HEADER.GUID
WHERE ISU_CONT.ATTR_NAME='ZPOT_AMT' AND ISU_CONT.ATTR_VALUE<>''
--      AND CRM_ITEM.NUMBER_EXT<>'0000000000' AND EXTA4.A4CANCELLED<>'X' 
      AND EXTA4.GUID IN (SELECT DISTINCT CONTRACTPOS FROM #NON_ZERO_POT_BILL_DETAILS_WITH_PRODUCT)

/*=====================================================================================================
      1. Combine CRM and ISU Data to check mismatches if any
      Q2-Count -> 3213247
=====================================================================================================*/
SELECT ISU_POT.REGION
      ,ISU_POT.BP
      ,ISU_POT.CA
	,ISU_POT.COMPANY_CODE
      ,ISU_POT.CONTRACT
	,ISU_POT.CUSTOMER_CLASS
      ,ISU_POT.FUEL
	,ISU_POT.ISU_PRODUCT 
      ,CRM_POT.CRM_CONTRACT
      ,CRM_POT.PRODUCT
      ,CRM_POT.POT_VALUE
      ,ISU_POT.BILL_DOC
      ,ISU_POT.INVOICE
      ,ISU_POT.BILL_START_DATE
      ,ISU_POT.BILL_END_DATE
      ,ISU_POT.TOTAL_AMT_DUE
      ,ISU_POT.DUE_DATE
      ,ISU_POT.POT_AMOUNT
INTO #CRM_ISU_POT_DETAILS_TBL FROM 
#NON_ZERO_POT_BILL_DETAILS_WITH_PRODUCT AS ISU_POT
FULL JOIN 
#CRM_POT_CUSTOMER AS CRM_POT 
ON ISU_POT.CONTRACTPOS=CRM_POT.ITEM_GUID

/*=====================================================================================================
	Derive all FICA 'PC' doc for those contracts
=====================================================================================================*/
	IF OBJECT_ID('dbo.TEMP_INVOICE_RECIVED_POT_FICA_DOC') IS NOT NULL
      DROP TABLE dbo.TEMP_INVOICE_RECIVED_POT_FICA_DOC

      SELECT DISTINCT RIGHT(DFKKOP.VTREF,10) AS CONTRACT
            ,DFKKOP.OPBEL
--            ,DFKKOP.AUGRD
            ,RIGHT(DFKKOP.XBLNR,12) AS INVOICE
            ,DFKKOP.BUDAT AS POSTING_DATE 
            ,ABS(SUM(BETRH)) AS FICA_POSTING_AMOUNT 
            ,DFKKKO.ERNAM
            ,TFK001T.HTEXT
            INTO dbo.TEMP_INVOICE_RECIVED_POT_FICA_DOC FROM
            ip1.DFKKOP AS DFKKOP
            LEFT JOIN
            ip1.DFKKKO AS DFKKKO ON DFKKOP.MANDT=DFKKKO.MANDT AND DFKKOP.OPBEL=DFKKKO.OPBEL
            LEFT JOIN
            ip1.TFK001T AS TFK001T ON TFK001T.SPRAS='E' AND TFK001T.HERKF=DFKKKO.HERKF
      WHERE RIGHT(VTREF,10) IN (SELECT CONTRACT FROM #NON_ZERO_POT_BILL_DETAILS_WITH_PRODUCT) 
      AND DFKKOP.BLART ='PC' AND DFKKOP.AUGRD <> '05' --AND DFKKOP.AUGST = '9'
      GROUP BY DFKKOP.VTREF,DFKKOP.OPBEL,DFKKOP.XBLNR,DFKKOP.BUDAT,DFKKKO.ERNAM,TFK001T.HTEXT


/*=====================================================================================================
      1. Attach to customer who recive POT in invoice itself.
      2. Attach 'PC' doc by finding manual posted PC doc after bill end date where FICA amount posted 
         are same that of expected Pay On Time
      3. Attach 'PC' doc by finding manual posted PC doc after bill end date where FICA amount posted 
         are different/split as that of expected Pay On Time
=====================================================================================================*/
--First Part
SELECT POT_CUSTOMER.*
      ,POT_FICA.INVOICE AS FICA_INVOICE
      ,POT_FICA.OPBEL AS FICA_DOC
      ,POT_FICA.ERNAM
      ,POT_FICA.FICA_POSTING_AMOUNT
      ,POT_FICA.HTEXT
      ,CASE WHEN POT_FICA.INVOICE<>'' THEN 'Y' ELSE 'N' END AS INVOICE_POSTED
INTO #TEMP1_CRM_ISU_POT_CUSTOMER 
FROM #CRM_ISU_POT_DETAILS_TBL AS POT_CUSTOMER
LEFT JOIN
dbo.TEMP_INVOICE_RECIVED_POT_FICA_DOC AS POT_FICA 
ON POT_CUSTOMER.CONTRACT = POT_FICA.CONTRACT AND POT_CUSTOMER.INVOICE = POT_FICA.INVOICE
AND POT_CUSTOMER.BILL_END_DATE  <= POT_FICA.POSTING_DATE

--Second part
SELECT POT_CUSTOMER.REGION
      ,POT_CUSTOMER.BP
      ,POT_CUSTOMER.CA
	,POT_CUSTOMER.COMPANY_CODE
      ,POT_CUSTOMER.CONTRACT
	,POT_CUSTOMER.CUSTOMER_CLASS
      ,POT_CUSTOMER.FUEL
	,POT_CUSTOMER.ISU_PRODUCT
      ,POT_CUSTOMER.CRM_CONTRACT
      ,POT_CUSTOMER.PRODUCT
      ,POT_CUSTOMER.POT_VALUE
      ,POT_CUSTOMER.BILL_DOC
      ,POT_CUSTOMER.INVOICE
      ,CAST(POT_CUSTOMER.BILL_START_DATE AS DATE) AS BILL_START_DATE
      ,CAST(POT_CUSTOMER.BILL_END_DATE AS DATE) AS BILL_END_DATE
      ,POT_CUSTOMER.TOTAL_AMT_DUE
      ,CAST(POT_CUSTOMER.DUE_DATE AS DATE) AS DUE_DATE
      ,POT_CUSTOMER.POT_AMOUNT
      ,POT_CUSTOMER.FICA_INVOICE
      ,CASE WHEN FICA_DOC.OPBEL IS NOT NULL THEN FICA_DOC.OPBEL ELSE POT_CUSTOMER.FICA_DOC END AS FICA_DOC
      ,CASE WHEN FICA_DOC.ERNAM IS NOT NULL THEN FICA_DOC.ERNAM ELSE POT_CUSTOMER.ERNAM END AS ERNAM
      ,CASE WHEN FICA_DOC.FICA_POSTING_AMOUNT IS NOT NULL THEN FICA_DOC.FICA_POSTING_AMOUNT 
            ELSE POT_CUSTOMER.FICA_POSTING_AMOUNT END AS FICA_POSTING_AMOUNT
      ,POT_CUSTOMER.INVOICE_POSTED
      ,CASE WHEN FICA_DOC.HTEXT IS NOT NULL THEN FICA_DOC.HTEXT ELSE POT_CUSTOMER.HTEXT END AS HTEXT
      ,CASE WHEN FICA_DOC.CONTRACT <> '' THEN 'Y' ELSE 'N' END AS FLAG
INTO #TEMP2_CRM_ISU_POT_CUSTOMER FROM 
#TEMP1_CRM_ISU_POT_CUSTOMER AS POT_CUSTOMER 
LEFT JOIN
dbo.TEMP_INVOICE_RECIVED_POT_FICA_DOC AS FICA_DOC 
ON POT_CUSTOMER.CONTRACT=FICA_DOC.CONTRACT AND POT_CUSTOMER.BILL_END_DATE <= FICA_DOC.POSTING_DATE 
AND POT_CUSTOMER.INVOICE_POSTED='N' AND POT_CUSTOMER.POT_AMOUNT=FICA_DOC.FICA_POSTING_AMOUNT
AND FICA_DOC.INVOICE=''

-- Third Part
SELECT POT_CUSTOMER.REGION
      ,POT_CUSTOMER.BP
      ,POT_CUSTOMER.CA
	,POT_CUSTOMER.COMPANY_CODE
      ,POT_CUSTOMER.CONTRACT
	,POT_CUSTOMER.CUSTOMER_CLASS
      ,POT_CUSTOMER.FUEL
	,POT_CUSTOMER.ISU_PRODUCT
      ,POT_CUSTOMER.CRM_CONTRACT
      ,POT_CUSTOMER.PRODUCT
      ,POT_CUSTOMER.POT_VALUE
      ,POT_CUSTOMER.BILL_DOC
      ,POT_CUSTOMER.INVOICE
      ,CAST(POT_CUSTOMER.BILL_START_DATE AS DATE) AS BILL_START_DATE
      ,CAST(POT_CUSTOMER.BILL_END_DATE AS DATE) AS BILL_END_DATE
      ,POT_CUSTOMER.TOTAL_AMT_DUE
      ,CAST(POT_CUSTOMER.DUE_DATE AS DATE) AS DUE_DATE
      ,POT_CUSTOMER.POT_AMOUNT
      ,POT_CUSTOMER.FICA_INVOICE
      ,CASE WHEN FICA_DOC.OPBEL IS NOT NULL THEN FICA_DOC.OPBEL ELSE POT_CUSTOMER.FICA_DOC END AS FICA_DOC
      ,CASE WHEN FICA_DOC.ERNAM IS NOT NULL THEN FICA_DOC.ERNAM ELSE POT_CUSTOMER.ERNAM END AS ERNAM
      ,CASE WHEN FICA_DOC.FICA_POSTING_AMOUNT IS NOT NULL THEN FICA_DOC.FICA_POSTING_AMOUNT 
            ELSE POT_CUSTOMER.FICA_POSTING_AMOUNT END AS FICA_POSTING_AMOUNT
      ,POT_CUSTOMER.INVOICE_POSTED
      ,CASE WHEN POT_CUSTOMER.FLAG='N' AND FICA_DOC.CONTRACT<>'' THEN 'Y' ELSE POT_CUSTOMER.FLAG END AS MANUAL_POSTING
      ,CASE WHEN FICA_DOC.HTEXT IS NOT NULL THEN FICA_DOC.HTEXT ELSE POT_CUSTOMER.HTEXT END AS HTEXT
INTO #TEMP3_CRM_ISU_POT_CUSTOMER FROM 
#TEMP2_CRM_ISU_POT_CUSTOMER AS POT_CUSTOMER 
LEFT JOIN
dbo.TEMP_INVOICE_RECIVED_POT_FICA_DOC AS FICA_DOC 
ON POT_CUSTOMER.CONTRACT=FICA_DOC.CONTRACT AND POT_CUSTOMER.BILL_END_DATE <= FICA_DOC.POSTING_DATE 
AND POT_CUSTOMER.INVOICE_POSTED='N' AND POT_CUSTOMER.POT_AMOUNT<>FICA_DOC.FICA_POSTING_AMOUNT
AND FICA_DOC.INVOICE='' AND POT_CUSTOMER.POT_AMOUNT <> 0.00
AND POT_CUSTOMER.FLAG='N'


/*====================================================================================================    
	1. Include Calender logic to populate other reporting related fields
	2. Join with consumption band AERESC_CONSUMPTION_BAND to get the consumption band
	3. Join with dbo.AERESC_CONTRACT_INSTALLATION_STATE to get State and Installation
	4. Join with dbo.AERESC_CONTRACT_UMS_BHW to populate exclusion flag for BHW/UMS
	DROP TABLE #CRM_ISU_POT_CUSTOMER_WITH_ATTRIBUTES
 ====================================================================================================*/

SELECT CONCAT((CASE WHEN DATEPART(MM,POT.DUE_DATE)>6 
               THEN DATEPART(YY,POT.DUE_DATE)+1 
               ELSE DATEPART(YY,POT.DUE_DATE) END - 1)
               ,'-'
               ,RIGHT(CASE WHEN DATEPART(MM,POT.DUE_DATE)>6 
                        THEN DATEPART(YY,POT.DUE_DATE)+1 
                        ELSE DATEPART(YY,POT.DUE_DATE) END, 2)) AS FISCAL_YEAR
	,CASE WHEN DATENAME(QQ,POT.DUE_DATE)=1 THEN 'Q3'
		WHEN DATENAME(QQ,POT.DUE_DATE)=2 THEN 'Q4'
		WHEN DATENAME(QQ,POT.DUE_DATE)=3 THEN 'Q1'
		WHEN DATENAME(QQ,POT.DUE_DATE)=4 THEN 'Q2' END AS FISCAL_QUARTER
	,CASE WHEN DATEPART(MONTH,POT.DUE_DATE) IN (1,4,7,10) THEN 'Month1'
		WHEN DATEPART(MONTH,POT.DUE_DATE) IN (2,5,8,11) THEN 'Month2'
		WHEN DATEPART(MONTH,POT.DUE_DATE) IN (3,6,9,12) THEN 'Month3' END AS REPORT_QMONTH
	,EOMONTH(DUE_DATE) AS SNAPSHOTDATE
	,POT.*
	,CONTRACT_INSTALLATION_STATE.STATE
	,CONTRACT_INSTALLATION_STATE.INSTALLATION
	,CONS_BAND.CONSUMPTION_BAND
	,CASE WHEN POT.FUEL='01' AND POT.CUSTOMER_CLASS='BUSI' AND REGION='SA' AND CONS_BAND.CONSUMPTION_BAND IN ('<40 MWH','>=40 < 100 MWH','>=100 < 160 MWH') THEN 'BUSI'
		WHEN POT.FUEL='01' AND POT.CUSTOMER_CLASS='BUSI' AND REGION IN ('QLD','NSW','ACT','TAS','VIC') AND CONS_BAND.CONSUMPTION_BAND IN ('<40 MWH','>=40 < 100 MWH') THEN 'BUSI'
		WHEN POT.FUEL='02' AND POT.CUSTOMER_CLASS='BUSI' AND CONS_BAND.CONSUMPTION_BAND IN ('<0.18 TJ','>=0.18 <1 TJ') THEN 'BUSI'
		WHEN POT.FUEL='01' AND POT.CUSTOMER_CLASS='BUSI' AND REGION='SA' AND CONS_BAND.CONSUMPTION_BAND IN ('>=160 < 750 MWH','>=750 MWH')  THEN 'C&I'
		WHEN POT.FUEL='01' AND POT.CUSTOMER_CLASS='BUSI' AND REGION  IN ('QLD','NSW','ACT','TAS','VIC') AND CONS_BAND.CONSUMPTION_BAND IN ('>=100 < 160 MWH','>=160 < 750 MWH','>=750 MWH') THEN 'C&I'
		WHEN POT.FUEL='02' AND POT.CUSTOMER_CLASS='BUSI' AND CONS_BAND.CONSUMPTION_BAND IN ('>=1 < 10 TJ','>=10 < 100 TJ','>=100 TJ') THEN 'C&I' 
	ELSE CUSTOMER_CLASS END AS DERIVED_CUSTOMER_CLASS
	,CASE WHEN POT.CONTRACT IS NOT NULL THEN 'N' ELSE 'Y' END AS EXCLUSION_FLAG
	INTO #CRM_ISU_POT_CUSTOMER_WITH_ATTRIBUTES FROM 
	#TEMP3_CRM_ISU_POT_CUSTOMER AS POT
	LEFT JOIN
	dbo.AERESC_CONSUMPTION_BAND AS CONS_BAND 
	ON POT.CONTRACT=CONS_BAND.CONTRACT AND LEFT(POT.BILL_END_DATE,7)=LEFT(CONS_BAND.SNAPSHOTDATE,7)
	LEFT JOIN
	dbo.AERESC_CONTRACT_INSTALLATION_STATE AS CONTRACT_INSTALLATION_STATE 
	ON POT.CONTRACT = CONTRACT_INSTALLATION_STATE.CONTRACT
	LEFT JOIN
	dbo.AERESC_CONTRACT_UMS_BHW AS UMS_BHW ON POT.CONTRACT = UMS_BHW.CONTRACT 
	AND POT.BILL_END_DATE BETWEEN CAST(UMS_BHW.VALIDFROM AS DATE) AND CAST(UMS_BHW.VALIDTO AS DATE)

/*=====================================================================================================
      1. Delete existing records present in the final table for reporting period.
      2. Joining above tables to get customer who have not recived POT due to any reason.
	SELECT TOP 10 * FROM #CRM_ISU_POT_CUSTOMER_WITH_ATTRIBUTES
=====================================================================================================*/

TRUNCATE TABLE dbo.TBL_AER_MISSED_POT

INSERT INTO dbo.TBL_AER_MISSED_POT
SELECT FISCAL_YEAR
	,FISCAL_QUARTER
	,REPORT_QMONTH
	,SNAPSHOTDATE
	,REGION
	,BP
	,CA
	,COMPANY_CODE
	,CONTRACT
	,CUSTOMER_CLASS
	,FUEL
	,ISU_PRODUCT
	,CRM_CONTRACT
	,PRODUCT
	,POT_VALUE
	,BILL_DOC
	,INVOICE
	,BILL_START_DATE
	,BILL_END_DATE
	,TOTAL_AMT_DUE
	,DUE_DATE
	,POT_AMOUNT
	,FICA_INVOICE
	,FICA_DOC
	,ERNAM
	,FICA_POSTING_AMOUNT
	,INVOICE_POSTED
	,MANUAL_POSTING
	,HTEXT
	,CASE WHEN DERIVED_CUSTOMER_CLASS='RESI' THEN 'Residential'
		  WHEN DERIVED_CUSTOMER_CLASS='BUSI' THEN 'Small Business' 
		  WHEN DERIVED_CUSTOMER_CLASS='C&I' THEN 'Large Business' END AS DERIVED_CUSTOMER_CLASS
	,CONSUMPTION_BAND
	,EXCLUSION_FLAG
FROM #CRM_ISU_POT_CUSTOMER_WITH_ATTRIBUTES


END