/*****************************************************************************************************
NAME:             USP_INSERT_AER_MISSED_POT_ROLL_UP_NUMBERS
OBJECT TYPE:        STORED PROCEDURE
CREATED:          SHIRSHA CHAKRABORTY
DESCRIPTION:        ROLLUP HARDSHIP
PARAMETERS:         @FISCAL_YEAR, @FISCAL_QUARTER
RECORDSETS RETURNED:    
FUNCTIONS USED & DESC:    NONE 
STORED PROCS USED & DESC: NONE 
ASSUMPTIONS:        
USAGE:
    DROP PROCEDURE dbo.USP_INSERT_AER_MISSED_POT_ROLL_UP_NUMBERS
    EXEC dbo.USP_INSERT_AER_MISSED_POT_ROLL_UP_NUMBERS '2018-19', 'Q2'
    SELECT TOP 1000 * FROM dbo.RR_ROLL_UP_NUMBERS WHERE ITEM_REF LIKE 'S3.21%'
    
  
MODIFICATIONS:
DATE			NAME					DESCRIPTION
02/04/2019     SHIRSHA CHAKRABORTY     INITIAL DEVELOPMENT
*****************************************************************************************************/

CREATE PROCEDURE [dbo].[USP_INSERT_AER_MISSED_POT_ROLL_UP_NUMBERS]
   @FISCAL_YEAR VARCHAR(8),
   @FISCAL_QUARTER VARCHAR(8)
-- add more stored procedure parameters here
AS
BEGIN 


DECLARE @RECORD_UPDATED_TIME DATETIME = GETDATE()

INSERT INTO dbo.RR_ROLL_UP_NUMBERS
SELECT A.REPORT_TYPE,A.HEADING,A.ITEM_REF,REGION,A.FUEL,COMPANY_CODE,A.ROLLUP_TYPE,DERIVED_CUSTOMER_CLASS,CONTRACT_TYPE
,SUM(VALUE) AS VALUE,SNAPSHOTDATE
,A.FISCAL_YEAR,A.FISCAL_QUARTER,A.REPORT_QMONTH,@RECORD_UPDATED_TIME AS RECORD_UPDATE_TIME 
FROM(
		SELECT 'AER' AS REPORT_TYPE
				,CASE WHEN FUEL='01' AND DERIVED_CUSTOMER_CLASS='Residential' 
							THEN 'Number of electricity residential customers that have missed pay on time discounts as a result of late or missed payment' 
					  WHEN FUEL='01' AND DERIVED_CUSTOMER_CLASS='Small Business'
							THEN 'Number of electricity small business customers that have missed pay on time discounts as a result of late or missed payment'
					  WHEN FUEL='02' AND DERIVED_CUSTOMER_CLASS='Residential' 
							THEN 'Number of gas residential customers that have missed pay on time discounts as a result of late or missed payment'
					  WHEN FUEL='02' AND DERIVED_CUSTOMER_CLASS='Small Business' 
							THEN 'Number of gas small business customers that have missed pay on time discounts as a result of late or missed payment' END AS HEADING
				,CASE WHEN FUEL='01' AND DERIVED_CUSTOMER_CLASS='Residential' THEN 'S3.21.a.i'
					  WHEN FUEL='01' AND DERIVED_CUSTOMER_CLASS='Small Business' THEN 'S3.21.a.ii'
					  WHEN FUEL='02' AND DERIVED_CUSTOMER_CLASS='Residential' THEN 'S3.21.b.i'
					  WHEN FUEL='02' AND DERIVED_CUSTOMER_CLASS='Small Business' THEN 'S3.21.b.ii' END AS ITEM_REF
				,REGION
				,CASE WHEN FUEL='01' THEN 'Electricity'
					  WHEN FUEL='02' THEN 'Gas' END AS FUEL
				,COMPANY_CODE
				,'Quarterly' AS ROLLUP_TYPE
				,DERIVED_CUSTOMER_CLASS
				,NULL AS CONTRACT_TYPE
				,COUNT(DISTINCT CONTRACT) AS VALUE 
				,CALMONTH.END_DATE AS SNAPSHOTDATE
				,CALMONTH.FISCAL_YEAR
				,CALMONTH.FISCAL_QUARTER
				,CALMONTH.REPORT_QMONTH
				FROM ( SELECT FISCAL_YEAR_YYYY_YY AS FISCAL_YEAR,
				FISCAL_QUARTER,
				MAX(FISCAL_QMONTH) AS REPORT_QMONTH,
				MIN(MONTH_START_DATE) AS START_DATE,
				MAX(MONTH_END_DATE) AS END_DATE  FROM dbo.TBL_AER_CALMONTH 
				WHERE FISCAL_YEAR_YYYY_YY = @FISCAL_YEAR AND FISCAL_QUARTER=@FISCAL_QUARTER GROUP BY FISCAL_YEAR_YYYY_YY, FISCAL_QUARTER ) AS CALMONTH 
				JOIN dbo.TBL_AER_MISSED_POT AS POT ON POT.SNAPSHOTDATE >= CALMONTH.START_DATE AND POT.SNAPSHOTDATE <= CALMONTH.END_DATE
				AND POT.REGION NOT IN ('VIC','WA')
				AND POT.POT_AMOUNT<>'0.00' 
				AND POT.DERIVED_CUSTOMER_CLASS IN ('Residential','Small Business')
				AND ((POT.FICA_INVOICE IS NULL AND POT.FICA_DOC IS NULL) OR 
				(POT.FICA_INVOICE IS NULL AND POT.FICA_DOC IS NOT NULL))
				GROUP BY POT.REGION,POT.FUEL,POT.COMPANY_CODE,POT.DERIVED_CUSTOMER_CLASS,CALMONTH.END_DATE,CALMONTH.FISCAL_YEAR,CALMONTH.FISCAL_QUARTER,CALMONTH.REPORT_QMONTH
				)A
		GROUP BY A.REPORT_TYPE,A.HEADING,A.ITEM_REF,REGION,A.FUEL,COMPANY_CODE,A.ROLLUP_TYPE,DERIVED_CUSTOMER_CLASS,CONTRACT_TYPE,A.FISCAL_YEAR,A.FISCAL_QUARTER,A.REPORT_QMONTH,A.SNAPSHOTDATE
END