select COUNT (CONTRACT_NUMBER), INSTALLATION_TYPE
FROM COMMERCIAL.HNODS_ST_BILL_CUSTOMER_MONTHLY_SNAPSHOT
WHERE CONTRACT_END_DATE ='9999-12-31'
AND month_start_date = current_date
AND FUEL = 'Gas'
GROUP BY INSTALLATION_TYPE


SELECT INSTALLATION_TYPE, SUM (CONSUMPTION_KWH)
FROM COMMERCIAL.HNODS_ST_BILL_LATEST_BILLS
WHERE START_BILLING_PERIOD >= '2019-01-01'
AND END_BILLING_PERIOD <= '2019-12-31'
GROUP BY INSTALLATION_TYPE